/** *****************************************************************************
 * Copyright (C) EDUARDO MARTÍN-SONSECA (maraloeDev)
 ***************************************************************************** */
package Ejercicio_4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class Ejercicio_4_Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_4_Calculadora
     */
    public Ejercicio_4_Calculadora() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        //Indico que en la cajita del resultado que no se pueda editar
        TextoResultado.setEditable(false);
        //Indico que los valores de las cajas de texto, sea 0
        this.TextoNumero1.setText(String.valueOf(0));
        this.TextoNumero2.setText(String.valueOf(0));
        this.TextoResultado.setText(String.valueOf(0));
        //Establezco que la propia ventana, que se genere en el centro
        this.setLocationRelativeTo(null);
        // Indico que cuando se habra la ventana, no se pueda aumentar
        this.setResizable(false);
        /* Establezco que en la acción por defecto cuando se seleccione 
        la Calculadora Estandar, que se muestres y oculten los botones
        'avanzados'
         */

        

        this.CalcEstandar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //'Habilito y deshabilito' la calculadora seleccionada
                Calc100tifica.setEnabled(true);
                CalcEstandar.setEnabled(false);

                TextoNumero2.setVisible(true);
                N2.setVisible(true);
                btnSuma.setVisible(true);
                btnResta.setVisible(true);
                btnMultiplicacion.setVisible(true);
                btnDivision.setVisible(true);
                btnClear.setVisible(true);
                btnLog.setVisible(false);
                btnSeno.setVisible(false);
                btnCos.setVisible(false);
                btnTan.setVisible(false);
                btnRC.setVisible(false);
                btnElevado.setVisible(false);

                // Salir.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        N1 = new javax.swing.JLabel();
        TextoNumero1 = new javax.swing.JTextField();
        N2 = new javax.swing.JLabel();
        TextoNumero2 = new javax.swing.JTextField();
        N3 = new javax.swing.JLabel();
        TextoResultado = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnSeno = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnRC = new javax.swing.JButton();
        btnElevado = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCalculadora = new javax.swing.JMenu();
        CalcEstandar = new javax.swing.JMenuItem();
        Calc100tifica = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        N1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N1.setText("Número 1 :");

        TextoNumero1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextoNumero1.setText("0");
        TextoNumero1.setToolTipText("");
        TextoNumero1.setAutoscrolls(false);
        TextoNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextoNumero1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextoNumero1FocusLost(evt);
            }
        });

        N2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N2.setText("Número 2 :");
        N2.setToolTipText("");

        TextoNumero2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextoNumero2.setText("0");
        TextoNumero2.setToolTipText("");
        TextoNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextoNumero2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextoNumero2FocusLost(evt);
            }
        });

        N3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        N3.setText("Resultado :");

        TextoResultado.setBackground(new java.awt.Color(51, 51, 255));
        TextoResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoResultado.setForeground(new java.awt.Color(255, 255, 255));
        TextoResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextoResultado.setText("0");
        TextoResultado.setToolTipText("");

        btnSuma.setText("+");
        btnSuma.setOpaque(true);
        btnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumaMouseClicked(evt);
            }
        });

        btnResta.setText("-");
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaMouseClicked(evt);
            }
        });

        btnMultiplicacion.setText("X");
        btnMultiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicacionMouseClicked(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisionMouseClicked(evt);
            }
        });

        btnLog.setText("log");
        btnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogMouseClicked(evt);
            }
        });

        btnSeno.setText("seno");
        btnSeno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSenoMouseClicked(evt);
            }
        });

        btnCos.setText("cos");
        btnCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCosMouseClicked(evt);
            }
        });

        btnTan.setText("tan");
        btnTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTanMouseClicked(evt);
            }
        });

        btnRC.setText("√");
        btnRC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMouseClicked(evt);
            }
        });

        btnElevado.setText("^");
        btnElevado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElevadoMouseClicked(evt);
            }
        });

        btnClear.setText("C");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        MenuCalculadora.setText("Calculadora");

        CalcEstandar.setText("Estandar");
        CalcEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcEstandarActionPerformed(evt);
            }
        });
        MenuCalculadora.add(CalcEstandar);

        Calc100tifica.setText("Cientifica");
        Calc100tifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc100tificaActionPerformed(evt);
            }
        });
        MenuCalculadora.add(Calc100tifica);

        jMenuBar1.add(MenuCalculadora);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(N1)
                                    .addComponent(N2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(N3)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnLog)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElevado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSuma)
                            .addComponent(btnResta)
                            .addComponent(btnMultiplicacion)
                            .addComponent(btnDivision))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLog)
                            .addComponent(btnSeno)
                            .addComponent(btnCos)
                            .addComponent(btnTan)
                            .addComponent(btnRC)
                            .addComponent(btnElevado)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N3)
                    .addComponent(TextoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextoNumero1FocusLost
        // En el FocusLost, si se sale del foco, el valor por defecto, es 0
        if (this.TextoNumero1.getText().isEmpty()) {
            this.TextoNumero1.setText(String.valueOf(0));
        } else { //controlo que es numérico
            try {
                Double.parseDouble(this.TextoNumero1.getText());
                this.TextoNumero1.setToolTipText(null);
            } catch (NumberFormatException ex) {
                this.TextoNumero1.requestFocus();
                this.TextoNumero1.setToolTipText("Debe introducir un dato numérico");
            }
        }
    }//GEN-LAST:event_TextoNumero1FocusLost

    private void TextoNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextoNumero2FocusLost
        // En el FocusLost, si se sale del foco, el valor por defecto, es 0
        if (this.TextoNumero2.getText().isEmpty()) {
            this.TextoNumero2.setText(String.valueOf(0));
        } else { //controlo que es numérico
            try {
                Double.parseDouble(this.TextoNumero2.getText());
                this.TextoNumero2.setToolTipText(null);
            } catch (NumberFormatException ex) {
                this.TextoNumero2.requestFocus();
                this.TextoNumero2.setToolTipText("Debe introducir un dato numérico");
            }
        }
    }//GEN-LAST:event_TextoNumero2FocusLost

    private void TextoNumero1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextoNumero1FocusGained
        //Cuando 'Entra' en el foco, selecciona todo lo que haya dentro de la caja de texto
        this.TextoNumero1.selectAll();
    }//GEN-LAST:event_TextoNumero1FocusGained

    private void TextoNumero2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextoNumero2FocusGained
        //Cuando 'Entra' en el foco, selecciona todo lo que haya dentro de la caja de texto
        this.TextoNumero2.selectAll();
    }//GEN-LAST:event_TextoNumero2FocusGained

    private void Calc100tificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc100tificaActionPerformed

        //'Habilito y deshabilito' la calculadora seleccionada
        Calc100tifica.setEnabled(false);
        CalcEstandar.setEnabled(true);

        N2.setVisible(false);
        TextoNumero2.setVisible(false);
        btnSuma.setVisible(false);
        btnResta.setVisible(false);
        btnMultiplicacion.setVisible(false);
        btnDivision.setVisible(false);
        btnLog.setVisible(true);
        btnSeno.setVisible(true);
        btnCos.setVisible(true);
        btnTan.setVisible(true);
        btnRC.setVisible(true);
        btnElevado.setVisible(true);
        btnClear.setVisible(true);
        // Salir.setVisible(true);
    }//GEN-LAST:event_Calc100tificaActionPerformed

    private void btnSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseClicked
        /* En este caso, agrego un evento 'MouseClicked', para todos los botones
           establezco en el teztoResultado, los metodos que implemento en la clase Calculadora.java con todas las operaciones*/
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            double numero2 = Double.parseDouble(this.TextoNumero2.getText());
            TextoResultado.setText(String.valueOf(Calculadora.sumarNumeros(numero1, numero2)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSumaMouseClicked

    private void btnRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            double numero2 = Double.parseDouble(this.TextoNumero2.getText());
            TextoResultado.setText(String.valueOf(Calculadora.restarNumeros(numero1, numero2)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaMouseClicked

    private void btnMultiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicacionMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            double numero2 = Double.parseDouble(this.TextoNumero2.getText());
            TextoResultado.setText(String.valueOf(Calculadora.multiplicarNumeros(numero1, numero2)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnMultiplicacionMouseClicked

    private void btnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            double numero2 = Double.parseDouble(this.TextoNumero2.getText());
            TextoResultado.setText(String.valueOf(Calculadora.dividirNumeros(numero1, numero2)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDivisionMouseClicked

    private void btnLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.logaritmoNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogMouseClicked

    private void btnSenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSenoMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.senoNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSenoMouseClicked

    private void btnCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCosMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.cosenoNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCosMouseClicked

    private void btnTanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTanMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.tangenteNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTanMouseClicked

    private void btnRCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.raizCuadradaNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRCMouseClicked

    private void btnElevadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElevadoMouseClicked
        try {
            double numero1 = Double.parseDouble(this.TextoNumero1.getText());
            TextoResultado.setText(String.valueOf(Calculadora.elevadoNumeros(numero1)));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe introducir datos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnElevadoMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // A la hora de limpiar todo, establezco todas las cajas de texto a 0
        TextoNumero1.setText("0");
        TextoNumero2.setText("0");
        TextoResultado.setText("0");
        JOptionPane.showMessageDialog(null, "Se han eliminado los numeros introducidos");
    }//GEN-LAST:event_btnClearMouseClicked

    private void CalcEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcEstandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcEstandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_4_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Calc100tifica;
    private javax.swing.JMenuItem CalcEstandar;
    private javax.swing.JMenu MenuCalculadora;
    private javax.swing.JLabel N1;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N3;
    private javax.swing.JTextField TextoNumero1;
    private javax.swing.JTextField TextoNumero2;
    private javax.swing.JTextField TextoResultado;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnElevado;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnRC;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeno;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
