/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio_2;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Eduardo Martín-Sonseca
 */
public class Ejercicio_2_Carrusel extends javax.swing.JFrame {

    private int retardo;
    private Timer t;
    private File[] archivoImagen;
    private int i = 0;

    /**
     * Creates new form Ejercicio_2_Carrusel
     */
    public Ejercicio_2_Carrusel() {
        initComponents();
        this.NumeroImgs.setMinimum(1);
        this.NumeroImgs.setMaximum(10);
        this.NumeroImgs.setMinorTickSpacing(1); //Calcular la distancia qie hay entre cada raya
        this.NumeroImgs.setMajorTickSpacing(1);
        this.NumeroImgs.setPaintLabels(true);
        this.NumeroImgs.setPaintTicks(true);
        this.NumeroImgs.setPaintTrack(true);
        this.NumeroImgs.setValue(2); //Valor por defecto
        this.NumeroImgs.setSnapToTicks(true);
        this.setMinimumSize(new Dimension(500, 0));
        retardo = this.NumeroImgs.getValue() * 100;
        t = new Timer(retardo, (ActionListener) this);

    }

    private void escalarImagen() {
        ImageIcon imagen = new ImageIcon(archivoImagen[i].getPath());
        Image imagenEscalada = imagen.getImage().getScaledInstance(this.jLabel1.getWidth(), this.jLabel1.getHeight(), Image.SCALE_SMOOTH);
        this.jLabel1.setIcon(new ImageIcon(imagenEscalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenida = new javax.swing.JLabel();
        NumeroImgs = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        MenuEleccion = new javax.swing.JMenuBar();
        imagenes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galería de imágenes");

        Bienvenida.setFont(Bienvenida.getFont().deriveFont(Bienvenida.getFont().getStyle() | java.awt.Font.BOLD));
        Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenida.setText("BIENVENIDO");
        Bienvenida.setToolTipText("");

        NumeroImgs.setMaximum(0);
        NumeroImgs.setPaintLabels(true);
        NumeroImgs.setPaintTicks(true);
        NumeroImgs.setSnapToTicks(true);
        NumeroImgs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NumeroImgsStateChanged(evt);
            }
        });

        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentResized(evt);
            }
        });

        imagenes.setText("Imágenes");
        imagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenesMouseClicked(evt);
            }
        });
        MenuEleccion.add(imagenes);

        setJMenuBar(MenuEleccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(NumeroImgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NumeroImgs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenesMouseClicked
        JFileChooser jfc = new JFileChooser("C:\\Users\\maraloed\\Pictures\\Camera Roll");
        jfc.setDialogTitle("Selecciona la imagen");
        jfc.setMultiSelectionEnabled(true);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png");
        jfc.addChoosableFileFilter(filtro); //Aplico el filtro
        File archivoImagen;
        int resp = jfc.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            archivoImagen = jfc.getSelectedFile();
            t.start();
            
        }
    }//GEN-LAST:event_imagenesMouseClicked

    private void jLabel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentResized
if(archivoImagen==null || archivoImagen.length==0) return;
          escalarImagen();

    }//GEN-LAST:event_jLabel1ComponentResized

    private void NumeroImgsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NumeroImgsStateChanged
        t.setDelay(this.NumeroImgs.getValue() * 1000);
        escalarImagen();
    }//GEN-LAST:event_NumeroImgsStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2_Carrusel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2_Carrusel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2_Carrusel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_2_Carrusel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ejercicio_2_Carrusel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JMenuBar MenuEleccion;
    private javax.swing.JSlider NumeroImgs;
    private javax.swing.JMenu imagenes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
