/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Problema1;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author maraloed
 */
public class Problema1 extends javax.swing.JFrame {

    /**
     * Creates new form Problema1
     */
    JButton boton = new JButton();
    JPanel panelContenedor = new JPanel();

    public Problema1() {
        initComponents();
        setFrame();
        creacionControles();
    }

    private void setFrame() {
        this.setTitle("Problema1");
        this.setLocationRelativeTo(null); //Para poner la pantalla en el medio
        this.setPreferredSize(new Dimension(500, 500)); //Establezco dimensiones a la ventana
        this.setResizable(false); //Para que no se agrande
        this.setContentPane(panelContenedor);
    }

    private void creacionControles() {
        //Crea un Array y defino las opciones que va a ver para ponerlo en el JOptionPane
        String[] opcionesTipo = {"FlowLayout", "BorderLayout"};
        //Defini la variable opciones que contiene los tipo de opciones que apareceran
        String opciones = (String) JOptionPane.showInputDialog(null, null, "Problema1", 1, null, opcionesTipo, opcionesTipo[0]);
        /*Si se selecciona la opcion de  tipo [0] "Layout" se le aparecera otro cuardo de dialogo
        que le pedira los numeros */

        if (opciones.equals(opcionesTipo[0])) {

            String botonesAelegir = JOptionPane.showInputDialog(null, "Numero de botones", "FlowLayout", 1);
//Creo un ArrayList donde se almacenaran los numeros

            ArrayList<Integer> numeros = new ArrayList<>();
            // Bucle for para añadir al ArrayList de numeros i
            for (int i = 0; i <= 10; i++) {
                numeros.add(i);
            }

            //Agrego el boton el resultado de i
            for (int i = 0; i <= 10; i++) {
                int num = numeros.get(i);
                boton = new JButton("" + num);
                panelContenedor.add(boton);
            }
            
        } else if (opciones.equals(opcionesTipo[1])) {
            this.setLocationRelativeTo(null);
            this.setTitle("BorderLayout");
            //Establezco una nueva dimension para la nueva ventana
            this.setPreferredSize(new Dimension(20, 50));
//Creacion de los JCheckBox
            JCheckBox cajaN = new JCheckBox();
            cajaN.setText("Norte");

            JCheckBox cajaS = new JCheckBox();
            cajaS.setText("Sur");

            JCheckBox cajaE = new JCheckBox();
            cajaE.setText("Este");

            JCheckBox cajaO = new JCheckBox();
            cajaO.setText("Oeste");

            JCheckBox cajaC = new JCheckBox();
            cajaC.setText("Centro");

            panelContenedor.add(cajaN);
            panelContenedor.add(cajaS);
            panelContenedor.add(cajaE);
            panelContenedor.add(cajaO);
            panelContenedor.add(cajaC);
            this.setContentPane(panelContenedor);
            
            if(cajaN.isSelected()){
                JPanel panel = new JPanel();
                panel.add(cajaC);
            }
            
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
